# -*- coding: utf-8 -*-
"""coursework_final_llms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9bHP0G90BOpSgWsCYHhLgd8kj6QhO2r
"""

!pip install colab-xterm
!pip install nltk
!pip install gcsfs==2024.12.0
!pip install fsspec==2024.12.0
!pip install lmqg transformers --quiet
!pip install pyemd
!pip install pandas
!pip install hf_xet

!pip uninstall numpy pyemd -y
!pip install numpy==1.26.0
!pip install pyemd

# Commented out IPython magic to ensure Python compatibility.
# %load_ext colabxterm

# Commented out IPython magic to ensure Python compatibility.
# %xterm

# Commented out IPython magic to ensure Python compatibility.
# %xterm

# === 2. Import all modules ===
import re, json, string, requests
import numpy as np
import pandas as pd
from datasets import load_dataset
from lmqg import QAAlignedF1Score, TransformersQG
from lmqg.language_model import AnswerNotFoundError
import random

# === 3. Utility functions ===
def normalize(text):
    text = str(text).strip().lower()
    text = re.sub(r'[' + re.escape(string.punctuation) + ']', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text

def format_qa_pairs(qa_pairs):
    return [f"question: {normalize(qa['question'])}, answer: {normalize(qa['answer'])}"
            for qa in qa_pairs if 'question' in qa and 'answer' in qa]

def extract_valid_json(text):
    try:
        match = re.search(r'\[\s*\{.*?\}\s*\]', text, re.DOTALL)
        return json.loads(match.group(0)) if match else None
    except:
        return None

def group_by_context(dataset_split):
    context_dict = {}
    for example in dataset_split:
        paragraph = example["paragraph"]
        context_dict.setdefault(paragraph, []).append({
            "question": example["question"],
            "answer": example["answer"]
        })
    return context_dict

# === 4. Ollama API-based QA generation ===
OLLAMA_URL = "http://localhost:11434/api/generate"

def generate_questions_answers_ollama(passage, model_name):
    prompt = f"""
    You will be given a passage. Your task is to generate a set of concise, factual, and non–open-ended question-answer pairs based solely on the passage. Each question must have a precise, short answer derived directly from the text.
    Requirements:
    1. Questions must be specific and fact-based, answerable only from the passage.
    2. Answers should be brief and match the passage content closely.
    3. Use the exact JSON format provided below, without any additional text or explanations.
    4. Generate a Maximum of 5 Question and Answer pairs
    JSON Structure:
    [
      {{
        "question": "Generated Question",
        "answer": "Generated Answer"
      }},
      ...
    ]
    Passage:
    \"\"\"{passage}\"\"\"
    Provide ONLY the JSON array as your final output.
    """

    payload = {
        "model": model_name,
        "prompt": prompt,
        "temperature": 0.1,
        "stream": False
    }

    try:
        response = requests.post(OLLAMA_URL, json=payload)
        response.raise_for_status()
        return extract_valid_json(response.json().get("response", "")) or []
    except Exception as e:
        print(f"[{model_name}] Error: {e}")
        return []

# === 5. Evaluation ===
def evaluate_model_on_dataset(model_name,
                              dataset_name,
                              dataset_split,
                              max_passages=100,
                              is_baseline=False,
                              baseline_model=None):
    context_dict = group_by_context(dataset_split)
    scorer_bs = QAAlignedF1Score(base_metric="bertscore")
    scorer_ms = QAAlignedF1Score(base_metric="moverscore")
    bert_scores, move_scores, csv_records = [], [], []

    # Randomly sample up to max_passages
    sampled_contexts = random.sample(
        list(context_dict.items()),
        min(max_passages, len(context_dict))
    )

    for passage, references in sampled_contexts:
        if is_baseline:
            predictions = [
                {"question": q, "answer": a}
                for q, a in baseline_model.generate_qa(passage)
            ]
        else:
            predictions = generate_questions_answers_ollama(passage, model_name)

        if not predictions or not references:
            continue

        pred_fmt = format_qa_pairs(predictions)
        ref_fmt  = format_qa_pairs(references)
        if not pred_fmt or not ref_fmt:
            continue

        try:
            bert_scores.append(
                np.mean(scorer_bs.get_score(pred_fmt, ref_fmt))
            )
            move_scores.append(
                np.mean(scorer_ms.get_score(pred_fmt, ref_fmt))
            )
            for qa in predictions:
                csv_records.append({
                    "model":   model_name,
                    "dataset": dataset_name,
                    "passage": passage[:100],
                    "question": qa["question"],
                    "answer":   qa["answer"]
                })
        except Exception as e:
            print(f"[{model_name}] Scoring error: {e}")

    return {
        "Model":            model_name,
        "Dataset":          dataset_name,
        "BERTScore (F1)":   round(np.mean(bert_scores), 4) if bert_scores else None,
        "MoverScore (F1)":  round(np.mean(move_scores), 4) if move_scores else None,
        "qa_csv":           pd.DataFrame(csv_records)
    }

# === 6. Load datasets ===
datasets = {
    "qg_squad": load_dataset("lmqg/qg_squad")["test"],
    "qg_squadshifts_amazon": load_dataset("lmqg/qg_squadshifts", "amazon")["test"],
    "qg_squadshifts_new_wiki": load_dataset("lmqg/qg_squadshifts", "new_wiki")["test"],
    "qg_squadshifts_nyt": load_dataset("lmqg/qg_squadshifts", "nyt")["test"],
    "qg_squadshifts_reddit": load_dataset("lmqg/qg_squadshifts", "reddit")["test"],
}
results_summary = []

# === 7. Run Ollama Models Evaluation ===
models = ["llama3:8b", "nemotron-mini", "phi"]
all_outputs = []

for model in models:
    for ds_name, ds_data in datasets.items():
        print(f"Running: {model} on {ds_name}")
        result = evaluate_model_on_dataset(model, ds_name, ds_data, max_passages=100)
        results_summary.append(result)
        result["qa_csv"].to_csv(f"{model}_{ds_name}_qa_pairs.csv", index=False)
        all_outputs.append(result["qa_csv"])

# === 9. Save Final Results ===
df_summary = pd.DataFrame(results_summary)
df_summary.to_csv("qa_eval_results_summary.csv", index=False)
print("\n=== Final Results ===")
print(df_summary)