# -*- coding: utf-8 -*-
"""coureswork_final_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GNZ70oseNWYdpHAiLsP_h_db5q9VCiN
"""

# Cell 1: Install & imports
!pip install lmqg transformers datasets --quiet
!pip install hf_xet

# 1. Completely remove numpy and pyemd
!pip uninstall numpy pyemd -y

# 2. Reinstall numpy at 1.26.0
!pip install numpy==1.26.0

# 3. Install pyemd FROM SOURCE (not wheel)
!pip install pyemd

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import numpy as np
from datasets import load_dataset
from lmqg import TransformersQG, QAAlignedF1Score
from lmqg.language_model import AnswerNotFoundError, ExceedMaxLengthError
import random
import torch

# Cell 2: load_and_group
def load_and_group(dataset_name, config=None, split="test"):
    """
    Loads a 🤗 dataset split and groups by passage.
    Returns: { passage_str: [ {question, answer}, … ] }
    """
    if config:
        ds = load_dataset(dataset_name, config)[split]
    else:
        ds = load_dataset(dataset_name)[split]

    context_dict = {}
    for ex in ds:
        p = ex["paragraph"]
        context_dict.setdefault(p, []).append({
            "question": ex["question"],
            "answer": ex["answer"]
        })
    return context_dict

# Cell 3: format_qa_list
def format_qa_list(qa_list):
    """
    Converts a list of {'question', 'answer'} dicts into standardized strings.
    """
    return [f"question: {qa['question']}, answer: {qa['answer']}" for qa in qa_list]

# Cell 4: generate_baseline_qa
def generate_baseline_qa(model, passage):
    """
    Uses the QG model to generate a list of {'question', 'answer'} dicts.
    If no answer is found in the passage, returns an empty list.
    """
    try:
        raw = model.generate_qa(passage)
        return [{"question": q, "answer": a} for q, a in raw]
    except AnswerNotFoundError:
        # no answer candidate found in this passage
        print(f"  [!] Skipping passage (no answer found)")
        return []

# Cell 5: score_qa_pairs
def score_qa_pairs(preds, refs, metric="bertscore"):
    """
    Computes QAAlignedF1Score (mean) for a single passage.
    preds & refs: lists of formatted strings.
    metric: "bertscore" or "moverscore"
    """
    scorer = QAAlignedF1Score(base_metric=metric)
    scores = scorer.get_score(preds, refs)
    return float(np.mean(scores))

# Cell 6: evaluate_dataset
def evaluate_dataset(model, context_dict, max_passages=100):
    """
    Runs generation+scoring on up to max_passages randomly selected passages.
    Skips passages that exceed the model's maximum input length.
    Returns: {
      'evaluated': int,
      'avg_bertscore': float,
      'avg_moverscore': float
    }
    """
    # Randomly shuffle the passages
    all_passages = list(context_dict.items())
    random.shuffle(all_passages)

    bert_scores, move_scores = [], []
    count = 0
    for passage, ref_qas in all_passages:
        if count >= max_passages:
            break

        try:
            pred_qas = generate_baseline_qa(model, passage)
            pred_fmt = format_qa_list(pred_qas)
            ref_fmt = format_qa_list(ref_qas)
            if not pred_fmt or not ref_fmt:
                continue

            bert_scores.append(score_qa_pairs(pred_fmt, ref_fmt, metric="bertscore"))
            move_scores.append(score_qa_pairs(pred_fmt, ref_fmt, metric="moverscore"))
            count += 1
        except ExceedMaxLengthError:
            print(f"  [!] Skipping passage (exceeds max length)")
            continue

    return {
        "evaluated": len(bert_scores),
        "avg_bertscore": float(np.mean(bert_scores)) if bert_scores else 0.0,
        "avg_moverscore": float(np.mean(move_scores)) if move_scores else 0.0
    }

if __name__ == "__main__":
    model = TransformersQG(language='en', model='lmqg/t5-large-squad-qg-ae')

    # load & group
    ctx_squad = load_and_group("lmqg/qg_squad", split="test")
    ctx_shift_amazon = load_and_group("lmqg/qg_squadshifts", config="amazon", split="test")
    ctx_shift_reddit = load_and_group("lmqg/qg_squadshifts", config="reddit", split="test")
    ctx_shift_nyt = load_and_group("lmqg/qg_squadshifts", config="nyt", split="test")
    ctx_shift_new_wiki = load_and_group("lmqg/qg_squadshifts", config="new_wiki", split="test")

    # evaluate each one
    print("→ qg_squad (100 passages):")
    with torch.no_grad():
        res1 = evaluate_dataset(model, ctx_squad, max_passages=100)
    print(f"   evaluated: {res1['evaluated']} | BERTScore: {res1['avg_bertscore']:.4f} | MoverScore: {res1['avg_moverscore']:.4f}")
    torch.cuda.empty_cache()

    print("→ qg_squadshifts_amazon (100 passages):")
    with torch.no_grad():
        res2 = evaluate_dataset(model, ctx_shift_amazon, max_passages=100)
    print(f"   evaluated: {res2['evaluated']} | BERTScore: {res2['avg_bertscore']:.4f} | MoverScore: {res2['avg_moverscore']:.4f}")
    torch.cuda.empty_cache()

    print("→ qg_squadshifts_reddit (100 passages):")
    with torch.no_grad():
        res3 = evaluate_dataset(model, ctx_shift_reddit, max_passages=100)
    print(f"   evaluated: {res3['evaluated']} | BERTScore: {res3['avg_bertscore']:.4f} | MoverScore: {res3['avg_moverscore']:.4f}")
    torch.cuda.empty_cache()

    print("→ qg_squadshifts_nyt (100 passages):")
    with torch.no_grad():
        res4 = evaluate_dataset(model, ctx_shift_nyt, max_passages=100)
    print(f"   evaluated: {res4['evaluated']} | BERTScore: {res4['avg_bertscore']:.4f} | MoverScore: {res4['avg_moverscore']:.4f}")
    torch.cuda.empty_cache()

    print("→ qg_squadshifts_new_wiki (100 passages):")
    with torch.no_grad():
        res5 = evaluate_dataset(model, ctx_shift_new_wiki, max_passages=100)
    print(f"   evaluated: {res5['evaluated']} | BERTScore: {res5['avg_bertscore']:.4f} | MoverScore: {res5['avg_moverscore']:.4f}")
    torch.cuda.empty_cache()

# Cell 8: Export results to CSV
import pandas as pd

def export_results_to_csv(results_dict, csv_path="evaluation_results.csv"):
    """
    Exports a dict of evaluation results to a CSV file.

    Args:
      results_dict: dict mapping dataset names to their result dicts, e.g.
        {
          "qg_squad": {
            "evaluated": 100,
            "avg_bertscore": 0.4321,
            "avg_moverscore": 0.3876
          },
          "qg_squadshifts": { ... }
        }
      csv_path:     path (including filename) where the CSV will be saved.
    """
    rows = []
    for ds_name, res in results_dict.items():
        rows.append({
            "dataset": ds_name,
            "passages_evaluated": res["evaluated"],
            "avg_bertscore_f1": res["avg_bertscore"],
            "avg_moverscore_f1": res["avg_moverscore"]
        })
    df = pd.DataFrame(rows)
    df.to_csv(csv_path, index=False)
    print(f"Results saved to {csv_path}")

# Example usage (after you have res1 and res2 from Cell 7):
results = {
    "qg_squad": res1,
    "qg_squadshifts_amazon": res2,
    "qg_squadshifts_reddit": res3,
    "qg_squadshifts_nyt": res4,
    "qg_squadshifts_new_wiki": res5

}
export_results_to_csv(results, "baseline_evaluation.csv")